const fs = require('fs');
const path = require('path');

const targetFile = path.join(__dirname, 'src', 'i18n', 'translations.ts');
let content = fs.readFileSync(targetFile, 'utf8');

// Sidebar Title Fixes
content = content.replace(/realCasesTitle:\s*'Real DBA Troubleshooting Scenarios'/, "realCasesTitle: 'Real Scenarios'");
content = content.replace(/realCasesTitle:\s*'Escenarios DBA Reales'/, "realCasesTitle: 'Escenarios Reales'");

const enKeys = [
    "        // Real Cases UI & Missing Keys",
    "        queryEvent: 'Query Event',",
    "        lockContention: 'Lock Contention',",
    "        waitDetected: 'Wait Detected',",
    "        ioBottleneck: 'I/O Bottleneck',",
    "        planIssue: 'Plan Issue',",
    "        stepLabel: 'Step',",
    "        stepObservation: 'Observation',",
    "        executionPipeline: 'Execution Pipeline',",
    "        tabSimulation: 'Simulation',",
    "        tabSchemaQuery: 'Schema & Query',",
    "        tabDetectionFix: 'Detection & Fix',",
    "        backToCases: 'Back to Cases',",
    "        explore: 'Explore',",
    "        // Blocker Case",
    "        caseBlocker: 'Blocking & Deadlocks',",
    "        caseBlockerDesc: 'A long running transaction blocks writers and readers. Watch the lock queue grow.',",
    "        blockerLog1: 'SPID 52 begins a transaction and updates a row, acquiring an exclusive (X) lock.',",
    "        blockerLog2: 'The UPDATE completes, but the transaction is NOT committed. The X lock is held.',",
    "        blockerLog3: 'SPIDs 53 and 54 attempt to UPDATE the same row. They are blocked (LCK_M_X) waiting for SPID 52.',",
    "        blockerLog4: 'SPID 52 finally COMMITs. SPIDs 53 and 54 acquire their locks and complete.',",
    "        blockerSpid52Running: 'UPDATE Orders',",
    "        blockerSpid52Lock: 'Holding X Lock (Uncommitted)',",
    "        blockerDone52: 'COMMIT',",
    "        caseBlockerBestPractice: 'Keep transactions as short as possible. Use Read Committed Snapshot Isolation (RCSI) to prevent writers from blocking readers.',",
    "        // Latch Case",
    "        caseLatch: 'TempDB / Page Latch Contention',",
    "        caseLatchDesc: 'Heavy concurrent inserts into a table with an identity column hitting the last page.',",
    "        latchLog1: 'Multiple SPIDs simultaneously execute an INSERT into EventLog.',",
    "        latchLog2: 'All threads try to modify the exact same physical B-tree page at the end of the index. PAGELATCH_EX contention occurs.',",
    "        latchLog3: 'Threads take turns acquiring the exclusive latch to write to the page.',",
    "        latchLog4: 'Inserts complete. The page is full and will split if another insert arrives.',",
    "        latchSpid60Running: 'INSERT EventLog',",
    "        latchDone: 'Done',",
    "        caseLatchBestPractice: 'Avoid highly sequential clustered index keys (like IDENTITY or sequential GUIDs) on extremely hot insert tables, or partition the table.',",
    "        // Plan Eviction",
    "        casePlanEviction: 'Plan Cache Bloat / Compiles',",
    "        casePlanEvictionDesc: 'Non-parameterized queries flooding the plan cache and causing CPU pressure.',",
    "        planLog1: 'Queries executing using existing compiled plans from the cache.',",
    "        planLog2: 'Ad-hoc queries flood the cache. Memory pressure triggers a cache eviction (clearing good plans).',",
    "        planLog3: 'Good queries now have to be recompiled from scratch (burning CPU).',",
    "        planLog4: 'New plans cached and execution resumes.',",
    "        casePlanBestPractice: 'Always parameterize your queries or use forced parameterization to promote plan reuse and save CPU cycles.',",
    "        // TempDB Case",
    "        caseTempDb: 'TempDB Allocation Contention',",
    "        caseTempDbDesc: 'Massive creation and dropping of temp tables causing PAGELATCH_UP on GAM/SGAM pages.',",
    "        tempdbLog1: '16 concurrent sessions call a stored proc that creates a #Temp table.',",
    "        tempdbLog2: 'All threads hit the single TempDB data file trying to allocate pages via GAM/SGAM, causing massive PAGELATCH_UP waits.',",
    "        tempdbLog3: 'Threads slowly acquire the allocation latch one by one.',",
    "        tempdbLog4: 'Stored procs complete and drop the #Temp tables.',",
    "        tempdbSpid80Running1: 'EXEC usp_Report',",
    "        tempdbSpid80Wait: 'Waiting for GAM page',",
    "        tempdbSpid80Running2: 'Allocating extents',",
    "        tempdbDone: 'Done',",
    "        tempdbBestPractice: 'Create multiple TempDB data files (usually 1 per logical core, up to 8) to spread out allocation contention.',",
    "        // LDF Case",
    "        caseLdfPlacement: 'Transaction Log Bottleneck',",
    "        caseLdfPlacementDesc: 'Data and Log files on the same slow disk causing WRITELOG waits.',",
    "        ldfLog1: 'Heavy INSERT/UPDATE workload generates log records in the Log Buffer.',",
    "        ldfLog2: 'Transactions attempt to COMMIT, flushing the Log Buffer to the LDF file on disk.',",
    "        ldfLog3: 'Because the disk is slow or shared with data files, WRITELOG waits accumulate.',",
    "        ldfLog4: 'Log hardened to disk, transactions finally complete.',",
    "        ldfSpid90Running1: 'Modifying Data',",
    "        ldfSpid90Wait: 'COMMIT (Waiting on Disk)',",
    "        ldfSpid90Wait2: 'Disk latency > 50ms',",
    "        ldfSpid90Running2: 'Hardened',",
    "        ldfBestPractice: 'Always place the Transaction Log (LDF) on the fastest available dedicated storage (SSD/NVMe) separate from Data files.',",
    "        // CXPACKET Case",
    "        caseCxpacket: 'CXPACKET (Parallelism)',",
    "        caseCxpacketDesc: 'A parallel query gets skewed data, causing fast threads to wait for slow threads.',",
    "        cxpLog1: 'Optimizer chooses DOP=8 for a massive GROUP BY query.',",
    "        cxpLog2: 'Thread 1 gets 95% of the data (skew). Threads 2-8 finish instantly and wait with CXPACKET.',",
    "        cxpLog3: 'Thread 1 still grinding through the data...',",
    "        cxpLog4: 'Thread 1 finishes. Exchange operator aggregates results.',",
    "        cxpSpid100Running1: 'Scanning Partition 1',",
    "        cxpSpid101Running1: 'Scanning Partition 2',",
    "        cxpSpid102Running1: 'Scanning Partition 3',",
    "        cxpSpid103Running1: 'Scanning Partition 4',",
    "        cxpSpid100Wait1: 'Waiting for Partition 1 (Slow)',",
    "        cxpSpid101Wait1: 'Finished (CXPACKET Wait)',",
    "        cxpSpid102Wait1: 'Finished (CXPACKET Wait)',",
    "        cxpSpid103Running2: 'Aggregating',",
    "        cxpacketBestPractice: 'Tune Cost Threshold for Parallelism (e.g. 50) and MAXDOP based on NUMA nodes. Fix data skew if possible.',"
].join('\n');

const esKeys = [
    "        // Real Cases UI & Missing Keys",
    "        queryEvent: 'Evento de Consulta',",
    "        lockContention: 'Contención de Bloqueo',",
    "        waitDetected: 'Espera Detectada',",
    "        ioBottleneck: 'Cuello de Botella I/O',",
    "        planIssue: 'Problema de Plan',",
    "        stepLabel: 'Paso',",
    "        stepObservation: 'Observación',",
    "        executionPipeline: 'Pipeline de Ejecución',",
    "        tabSimulation: 'Simulación',",
    "        tabSchemaQuery: 'Esquema y Consulta',",
    "        tabDetectionFix: 'Detección y Solución',",
    "        backToCases: 'Volver a Casos',",
    "        explore: 'Explorar',",
    "        // Blocker Case",
    "        caseBlocker: 'Bloqueos y Deadlocks',",
    "        caseBlockerDesc: 'Una transacción larga bloquea a lectores y escritores. Observa cómo crece la cola de locks.',",
    "        blockerLog1: 'El SPID 52 inicia una transacción, actualiza una fila y adquiere un candado exclusivo (X).',",
    "        blockerLog2: 'El UPDATE termina, pero NO hay COMMIT. El candado X se mantiene.',",
    "        blockerLog3: 'Los SPIDs 53 y 54 intentan un UPDATE en la misma fila. Quedan bloqueados (LCK_M_X) esperando al SPID 52.',",
    "        blockerLog4: 'Finalmente, el SPID 52 hace COMMIT. Los demás adquieren sus candados y terminan.',",
    "        blockerSpid52Running: 'UPDATE Orders',",
    "        blockerSpid52Lock: 'Candado X (Sin Commit)',",
    "        blockerDone52: 'COMMIT',",
    "        caseBlockerBestPractice: 'Mantén las transacciones cortas. Usa RCSI (Read Committed Snapshot Isolation) para que los escritores no bloqueen a los lectores.',",
    "        // Latch Case",
    "        caseLatch: 'TempDB / Contención de Latch',",
    "        caseLatchDesc: 'Inserciones masivas en una tabla con IDENTITY atacando la última página del índice.',",
    "        latchLog1: 'Múltiples SPIDs ejecutan simultáneamente INSERT en EventLog.',",
    "        latchLog2: 'Todos los hilos intentan modificar exactamente la misma página física del B-tree. Ocurre contención PAGELATCH_EX.',",
    "        latchLog3: 'Los hilos se turnan arduamente para adquirir el latch exclusivo de la página.',",
    "        latchLog4: 'Terminan los inserts. La página se llenó y causará un Page Split con el próximo insert.',",
    "        latchSpid60Running: 'INSERT EventLog',",
    "        latchDone: 'Completado',",
    "        caseLatchBestPractice: 'Evita llaves clúster altamente secuenciales (IDENTITY / GUID secuencial) en tablas de uso hiper-intensivo, o particiónalas.',",
    "        // Plan Eviction",
    "        casePlanEviction: 'Saturación de Caché de Planes',",
    "        casePlanEvictionDesc: 'Consultas no parametrizadas inundando el caché y causando presión de CPU por compilaciones.',",
    "        planLog1: 'Las consultas se ejecutan reusando los planes compilados en caché.',",
    "        planLog2: 'Miles de consultas Ad-hoc inundan la memoria. El servidor limpia el caché (evicción) para sobrevivir.',",
    "        planLog3: 'Las consultas buenas ahora deben recompilarse desde cero (quemando CPU).',",
    "        planLog4: 'Nuevos planes guardados, la ejecución se reanuda.',",
    "        casePlanBestPractice: 'Parametriza SIEMPRE tus consultas (o usa Forced Parameterization) para promover el reuso de planes y salvar la CPU.',",
    "        // TempDB Case",
    "        caseTempDb: 'Contención de Allocation en TempDB',",
    "        caseTempDbDesc: 'Creación y destrucción masiva de tablas temporales causando PAGELATCH_UP en páginas GAM/SGAM.',",
    "        tempdbLog1: '16 sesiones llaman un Stored Procedure que crea una tabla #Temp.',",
    "        tempdbLog2: 'Todos los hilos atacan el ÚNICO archivo de datos de TempDB para reservar espacio, causando esperas PAGELATCH_UP.',",
    "        tempdbLog3: 'Los hilos logran obtener poco a poco el Latch de allocation.',",
    "        tempdbLog4: 'Los stored procs terminan y dropean las tablas #Temp.',",
    "        tempdbSpid80Running1: 'EXEC usp_Report',",
    "        tempdbSpid80Wait: 'Esperando página GAM',",
    "        tempdbSpid80Running2: 'Extents asignados',",
    "        tempdbDone: 'Completado',",
    "        tempdbBestPractice: 'Crea múltiples archivos de datos para el TempDB (usualmente 1 por core lógico, max 8) para diluir la contención de allocation.',",
    "        // LDF Case",
    "        caseLdfPlacement: 'Cuello de Botella Transaccional (LDF)',",
    "        caseLdfPlacementDesc: 'Archivos Data y Log en el mismo disco lento causando agonía en esperas WRITELOG.',",
    "        ldfLog1: 'Carga pesada de INSERT/UPDATE genera registros en el Log Buffer.',",
    "        ldfLog2: 'Las transacciones hacen COMMIT. El Log Buffer debe vaciarse al archivo físico LDF.',",
    "        ldfLog3: 'El disco magnético es lento o está saturado de lecturas. Ocurren esperas WRITELOG extremas.',",
    "        ldfLog4: 'El Log finalmente se escribe al disco. Las transacciones avanzan.',",
    "        ldfSpid90Running1: 'Modificando Datos',",
    "        ldfSpid90Wait: 'COMMIT (Esperando I/O)',",
    "        ldfSpid90Wait2: 'Latencia > 50ms',",
    "        ldfSpid90Running2: 'Afianzado en Disco',",
    "        ldfBestPractice: 'Siempre coloca el archivo de Transacciones (LDF) en el disco dedicado MÁS RÁPIDO posible (SSD/NVMe), separado de los .mdf.',",
    "        // CXPACKET Case",
    "        caseCxpacket: 'CXPACKET y Skew de Datos',",
    "        caseCxpacketDesc: 'Una consulta paralela tiene mala distribución de datos. Los hilos rápidos esperan a los lentos.',",
    "        cxpLog1: 'El Optimizador elige DOP=8 para una gigantesca consulta GROUP BY.',",
    "        cxpLog2: 'El Hilo 1 se lleva el 95% de los datos (Skew). Los hilos 2-8 terminan al instante y esperan en CXPACKET.',",
    "        cxpLog3: 'El Hilo 1 sigue sudando frío procesando su enorme partición...',",
    "        cxpLog4: 'El Hilo 1 termina. El operador Exchange consolida los resultados finales.',",
    "        cxpSpid100Running1: 'Leyendo Partición 1',",
    "        cxpSpid101Running1: 'Leyendo Partición 2',",
    "        cxpSpid102Running1: 'Leyendo Partición 3',",
    "        cxpSpid103Running1: 'Leyendo Partición 4',",
    "        cxpSpid100Wait1: 'Sufriendo (Lento)',",
    "        cxpSpid101Wait1: 'Esperando (CXPACKET)',",
    "        cxpSpid102Wait1: 'Esperando (CXPACKET)',",
    "        cxpSpid103Running2: 'Consolidando',",
    "        cxpacketBestPractice: 'Ajusta el \"Cost Threshold for Parallelism\" (>50) y el MAXDOP acorde a los nodos NUMA. Arregla el skew de tabla.',"
].join('\n');

content = content.replace(/(qeRemediationTitle:\s*'.*?',)/, "$1\n" + enKeys);
content = content.replace(/(qeRemediationTitle:\s*'.*?',\s*(?:\r\n|\n|.)*?)(qeRemediationTitle:\s*'.*?',)/, "$1$2\n" + esKeys);

fs.writeFileSync(targetFile, content);
console.log('Successfully cleanly injected Real Cases strings!');
